# Generated by Django 4.2.5 on 2023-11-08 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelsites', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
