# Generated by Django 4.2.7 on 2023-11-16 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_phone', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_first', models.CharField(max_length=20)),
                ('emp_last', models.CharField(max_length=20)),
                ('contact_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepages.contact_information')),
            ],
        ),
    ]
