# Generated by Django 4.2.7 on 2023-11-16 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_state_employee_emp_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_title',
            field=models.CharField(blank=True, choices=[('Ms.', 'MISS'), ('Mr.', 'MR.'), ('Mrs.', 'MRS.'), ('Miss', 'Miss'), ('Mx.', 'MX.')], max_length=4, null=True),
        ),
        migrations.CreateModel(
            name='Skill_Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_rating', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepages.skill')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='emp_skills',
            field=models.ManyToManyField(through='homepages.Skill_Level', to='homepages.skill'),
        ),
    ]
