# Generated by Django 4.2.7 on 2023-11-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepages', '0002_state_employee_emp_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_title',
            field=models.CharField(blank=True, choices=[('Ms.', 'MISS'), ('Mr.', 'MR.'), ('Mrs.', 'MRS.'), ('Miss', 'Miss'), ('Mx.', 'MX.')], max_length=4, null=True),
        ),
    ]
